<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
		<WarningsAsErrors>Nullable</WarningsAsErrors>
  </PropertyGroup>

	<ItemGroup>
	  <ProjectReference Include="..\MatchMaking.Service.Dto\MatchMaking.Service.WebApi.Dto.csproj" />
	</ItemGroup>

</Project>
